// Auto-generated parameters from Edge Impulse TFLite flatbuffers
#ifndef SL_TFLITE_MICRO_MODEL_PARAMETERS_H
#define SL_TFLITE_MICRO_MODEL_PARAMETERS_H

// Definitions generated from "tflite_learn_23.tflite"
#define SL_TFLITE_MODEL_AVERAGE_WINDOW_DURATION_MS    440
#define SL_TFLITE_MODEL_CLASSES                       {"glass_breaking", "noise"}
#define SL_TFLITE_MODEL_DATE                          "2025-01-01T00:00:00.000Z"
#define SL_TFLITE_MODEL_DETECTION_THRESHOLD           60       // 0.6 * 100 from EI_CLASSIFIER_THRESHOLD
#define SL_TFLITE_MODEL_FE_ACTIVITY_DETECTION_ALPHA_A 0.5f
#define SL_TFLITE_MODEL_FE_ACTIVITY_DETECTION_ALPHA_B 0.8f
#define SL_TFLITE_MODEL_FE_ACTIVITY_DETECTION_ARM_THRESHOLD 0.75f
#define SL_TFLITE_MODEL_FE_ACTIVITY_DETECTION_ENABLE  false
#define SL_TFLITE_MODEL_FE_ACTIVITY_DETECTION_TRIP_THRESHOLD 0.8f
#define SL_TFLITE_MODEL_FE_DC_NOTCH_FILTER_COEFFICIENT 0.95f
#define SL_TFLITE_MODEL_FE_DC_NOTCH_FILTER_ENABLE     true
#define SL_TFLITE_MODEL_FE_FFT_LENGTH                 256      // từ ei_dsp_config_22.fft_length
#define SL_TFLITE_MODEL_FE_FILTERBANK_LOWER_BAND_LIMIT 125.0f
#define SL_TFLITE_MODEL_FE_FILTERBANK_N_CHANNELS      40       // num_filters trong ei_dsp_config_22
#define SL_TFLITE_MODEL_FE_FILTERBANK_UPPER_BAND_LIMIT 8000.0f
#define SL_TFLITE_MODEL_FE_LOG_SCALE_ENABLE           true
#define SL_TFLITE_MODEL_FE_LOG_SCALE_SHIFT            6
#define SL_TFLITE_MODEL_FE_NOISE_REDUCTION_ENABLE     true
#define SL_TFLITE_MODEL_FE_NOISE_REDUCTION_EVEN_SMOOTHING 0.025f
#define SL_TFLITE_MODEL_FE_NOISE_REDUCTION_MIN_SIGNAL_REMAINING 0.03f
#define SL_TFLITE_MODEL_FE_NOISE_REDUCTION_ODD_SMOOTHING 0.06f
#define SL_TFLITE_MODEL_FE_NOISE_REDUCTION_SMOOTHING_BITS 10
#define SL_TFLITE_MODEL_FE_PCAN_ENABLE                false
#define SL_TFLITE_MODEL_FE_PCAN_GAIN_BITS             21
#define SL_TFLITE_MODEL_FE_PCAN_OFFSET                80.0f
#define SL_TFLITE_MODEL_FE_PCAN_STRENGTH              0.95f
#define SL_TFLITE_MODEL_FE_QUANTIZE_DYNAMIC_SCALE_ENABLE true
#define SL_TFLITE_MODEL_FE_QUANTIZE_DYNAMIC_SCALE_RANGE_DB 40.0f
#define SL_TFLITE_MODEL_FE_SAMPLE_LENGTH_MS           1000
#define SL_TFLITE_MODEL_FE_SAMPLE_RATE_HZ             16000
#define SL_TFLITE_MODEL_FE_WINDOW_SIZE_MS             20
#define SL_TFLITE_MODEL_FE_WINDOW_STEP_MS             10
#define SL_TFLITE_MODEL_HASH                          "edgeimpulse_741591"
#define SL_TFLITE_MODEL_LATENCY_MS                    200
#define SL_TFLITE_MODEL_MINIMUM_COUNT                 2
#define SL_TFLITE_MODEL_NAME                          "Audio Classification - Glass breaking"
#define SL_TFLITE_MODEL_RUNTIME_MEMORY_SIZE           14214   // EI_CLASSIFIER_TFLITE_LARGEST_ARENA_SIZE
#define SL_TFLITE_MODEL_SUPPRESSION_MS                900
#define SL_TFLITE_MODEL_VERBOSE_MODEL_OUTPUT_LOGS     false
#define SL_TFLITE_MODEL_VERSION                       3
#define SL_TFLITE_MODEL_VOLUME_GAIN                   0

#endif // SL_TFLITE_MICRO_MODEL_PARAMETERS_H
